# Generated by Django 4.2.19 on 2025-03-29 03:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=50, unique=True, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
            ],
            options={
                'verbose_name': 'cause',
                'verbose_name_plural': 'causes',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='amount')),
                ('message', models.TextField(blank=True, default='', verbose_name='message')),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, help_text='A clear description of the objective.', max_length=255)),
                ('target_value', models.DecimalField(decimal_places=2, help_text='The specific, measurable target to be achieved.', max_digits=10)),
                ('unit_of_measurement', models.CharField(blank=True, help_text="The unit in which the target is measured (e.g., 'cans', 'trees', 'students', 'hours').", max_length=50)),
                ('deadline', models.DateField(blank=True, help_text='The deadline for achieving this objective.', null=True)),
                ('current_progress', models.IntegerField(default=0, help_text='The current progress towards the target (numerical value).')),
                ('notes', models.TextField(blank=True, help_text='Any additional notes or updates on this objective.')),
                ('is_completed', models.BooleanField(default=False, help_text='Indicates if this objective has been completed.')),
                ('completion_date', models.DateTimeField(blank=True, help_text='The date and time when this objective was completed.', null=True)),
            ],
            options={
                'verbose_name': 'objective',
                'verbose_name_plural': 'objectives',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('intended_impact', models.TextField(blank=True, default='', verbose_name='intended impact')),
                ('beneficaries', models.TextField(blank=True, default='', verbose_name='beneficiaries')),
                ('target_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='target amount')),
                ('current_amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='current amount')),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Proposed', 'Proposed'), ('Funding', 'Funding'), ('In Progress', 'In Progress'), ('On Hold', 'On Hold'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Draft', max_length=12, verbose_name='status')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='location')),
                ('deadline', models.DateField(blank=True, verbose_name='deadline')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='completion date')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(blank=True, choices=[('Orgainizer', 'Orgainizer'), ('Volunteer', 'Volunteer'), ('Follower', 'Follower')], default='Follower', max_length=10, verbose_name='role')),
            ],
            options={
                'verbose_name': 'project participant',
                'verbose_name_plural': 'project participants',
            },
        ),
        migrations.CreateModel(
            name='ProjectUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, default='', verbose_name='content')),
            ],
            options={
                'verbose_name': 'project update',
                'verbose_name_plural': 'project updates',
            },
        ),
        migrations.CreateModel(
            name='UserCause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cause', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='causes.cause', verbose_name='cause')),
            ],
            options={
                'verbose_name': 'user cause',
                'verbose_name_plural': 'user causes',
            },
        ),
    ]
