# Generated by Django 4.2.19 on 2025-05-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0003_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.AddField(
            model_name='project',
            name='overall_progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='overall progress'),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, default='', verbose_name='problem'),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, default='', verbose_name='solution'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='target amount'),
        ),
    ]
