# Generated by Django 4.2.19 on 2025-05-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0004_remove_project_description_project_overall_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='deadline'),
        ),
    ]
