# Generated by Django 4.2.19 on 2025-05-23 05:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('causes', '0005_alter_project_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assignments', to=settings.AUTH_USER_MODEL, verbose_name='assignees'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='scheduled at'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='task',
            field=models.CharField(blank=True, max_length=150, verbose_name='task'),
        ),
    ]
